"""Generated by tools/gen_font.py from consola.ttf at 22 px. Do not edit by hand."""
import base64
import zlib

CELL_W = 12
CELL_H = 23
ROW_BYTES = 2
FIRST = 32
LAST = 126

_BLOB = (
    "eNqlWL9r5FYQnrezvOdCll0FF+K4P2G5g7CFMalS5Y9wcVx1hK2Ciy0WEswVIlx1GGLyNxiuuSqIELbaImUgEFQcrkwQKYIg"
    "Qs43o92VLL23XifvM/tz9DRv5ptvZk301HXuBW2fH64rs8F+ux/zMZ/wiamP6iO56t7du7fmrUkp7VlmQMEVf0Vf0tc0p5Jy"
    "k/Nz99y+cDVXNFG0K4nO7Et+yT+ZP3DlOb67cb+5VbSKlu5b7vtRUGVSxQo7T2lub+3SXfL3XLsyDsdkj2UWJlNb8e9ki6m+"
    "l88zWhhax0u+kU9zPe/CtJD3ue5yQgcPPHk1Krmgkl+N9vRo633taveEk2yvLuCJ+DKHL6FVmtLQf2Bb4fOFidsobGJ5rNGK"
    "ADvIZskJx866pbt139gzG9vYJWBP4blnThXwSc/UReUq5zmXMIWJG58yk9MMuUx2WH+3ti0RkwWTA7gylccT7AbcaP2k5hK4"
    "P7o/ak4+tK5wnoga4ASse+PRv3fOBU/Vtja1xAYrsokrvTERZiCs6zM2zJsh5lNvxgsDTzhyEV+z5P1a949dxT4OaK2xZfEA"
    "Nq7U+2Twer43LwI8CVrna8ZeDP1HTrJ1DhM8zqTumHZyV6PTeQ6tA61m1DLugbuAKw+rd7Om4InYaLy5MMVayyYa80EmzQlH"
    "NsLf7eFfhx8OfxBEv4//cR+YaYS0RQ9qL0c0CnqnrDqQPHEFvyX4oM+QVU0ugZT1tcONbIRc+llVusRGFOOuG8SU2NIV7Ikb"
    "1XzJVrm3XVBZMJIe4Xfv9f7WgoDf48brJVRCuWhDfnfdrZvYbZffE1/PDPhtKrMY4Bd8euHxW2pMetQb4BR4Q3e0otRI9Q2t"
    "kwD8WhU7wY/uvX1v/7avATsejUfRKPLxBIpqn9nP7OeA2C6BS3sJzbUuoBAubkImlzYvEJGSAhxseGfBVjBvVy537Y3KP8iO"
    "Fh2PRCnTlt+0kq7fqJcN7D1STuvEoRprLdfeauj20+HEtItV7VK/PeqzOWLsxPeEpZo/mkJr22ctebNjO34N3CKfyCpyKxn2"
    "eSLd8QqqUah2FvQRGh5BxV08tEagEGTR+itT6BW7TqkayYvOFNR07aF2Yi8zod0Qm20tAM281E5SzcwE9RYttd0+XNLiEYjN"
    "wx7yK+bZA9TW2NL/XNLHNzU5edK01c5TosvEpWgbx5hMK74YDfRhjTtYJ5sKgnqn7NfvTUcp+XTU1lgiE6XxTWGCgnW6kg6u"
    "SL2etFktWSKouql1hClsoIOZy91M8yh2/awH94aOpdtKlt1xSlVn1KfxxmTd21r0J4d8nZ050NPvgWrKbNRMZn4VX5if0dnm"
    "g+xIPlbmDt+Igot+px79HnoQ9qRdL/CL5U9V5C5C1p/2iElfaVutigL63dl7wMGQjntZxRvO9a1XyPOp7Eq7+3yXgxHmrMJk"
    "2G0c8LthWw1176kO58GY9GO3uxqaqAlEv9+p1obVgFXDJX+Ngl+76x3ZEU1uekKuCn4lOmEf9UTnwhtcMVNuTekZxd6ZBnxe"
    "/5IW1R1yMEOUWo5OdD6Z9Jibc8bh/yqE++Zppxa+EJ2XeRqvNjjXX6OngbMmdIYoLt3CE7t/Af1cHeo="
)

GLYPHS = zlib.decompress(base64.b64decode(_BLOB))
GLYPH_BYTES = CELL_H * ROW_BYTES


def glyph_rows(ch):
    """Row bitmasks (bit x set = pixel on) for a character; unknown characters draw as space."""
    code = ord(ch)
    if code < FIRST or code > LAST:
        code = FIRST
    base = (code - FIRST) * GLYPH_BYTES
    return [int.from_bytes(GLYPHS[base + y * ROW_BYTES: base + (y + 1) * ROW_BYTES], 'little') for y in range(CELL_H)]
