"""Generates fcam_font.py: a fixed-cell 1-bit bitmap font (ASCII 32..126) rendered with Pillow on a
development PC, so the overlay can draw text on the headset with the Python standard library only.

    python steamframe/overlay/tools/gen_font.py [path-to-monospace.ttf] [pixel-size]
"""
import base64
import sys
import zlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

font_path = sys.argv[1] if len(sys.argv) > 1 else r"C:\Windows\Fonts\consola.ttf"
size = int(sys.argv[2]) if len(sys.argv) > 2 else 22
font = ImageFont.truetype(font_path, size)

chars = [chr(c) for c in range(32, 127)]
advance = max(int(round(font.getlength(c))) for c in chars)
ascent, descent = font.getmetrics()
cell_w, cell_h = advance, ascent + descent

rows = []
for ch in chars:
    img = Image.new("L", (cell_w, cell_h), 0)
    ImageDraw.Draw(img).text((0, 0), ch, font=font, fill=255)
    bits = bytearray()
    for y in range(cell_h):
        row = 0
        for x in range(cell_w):
            if img.getpixel((x, y)) > 110:
                row |= 1 << x
        bits += row.to_bytes((cell_w + 7) // 8, "little")
    rows.append(bytes(bits))

blob = base64.b64encode(zlib.compress(b"".join(rows), 9)).decode("ascii")
out = Path(__file__).resolve().parent.parent / "fcam_font.py"
lines = [
    '"""Generated by tools/gen_font.py from %s at %d px. Do not edit by hand."""' % (Path(font_path).name, size),
    "import base64",
    "import zlib",
    "",
    "CELL_W = %d" % cell_w,
    "CELL_H = %d" % cell_h,
    "ROW_BYTES = %d" % ((cell_w + 7) // 8),
    "FIRST = 32",
    "LAST = 126",
    "",
    "_BLOB = (",
]
for i in range(0, len(blob), 96):
    lines.append('    "%s"' % blob[i:i + 96])
lines += [
    ")",
    "",
    "GLYPHS = zlib.decompress(base64.b64decode(_BLOB))",
    "GLYPH_BYTES = CELL_H * ROW_BYTES",
    "",
    "",
    "def glyph_rows(ch):",
    '    """Row bitmasks (bit x set = pixel on) for a character; unknown characters draw as space."""',
    "    code = ord(ch)",
    "    if code < FIRST or code > LAST:",
    "        code = FIRST",
    "    base = (code - FIRST) * GLYPH_BYTES",
    "    return [int.from_bytes(GLYPHS[base + y * ROW_BYTES: base + (y + 1) * ROW_BYTES], 'little') for y in range(CELL_H)]",
    "",
]
out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out} cell {cell_w}x{cell_h}, {len(blob)} chars of data")
